### ISSUE TITLE
Item IDs and Scene Changes

### ISSUE THREAD

**Issue by jaku** [WarpWorld/CCPack-PC-ContentWarning#2]
https://discord.com/channels/168430302954258433/1280304411075280948/1280304411075280948

Looks like scene name change may have happened, and item IDs are changed again.

Might be best to try and do a scan for all the items to determine the IDs and use that going forward.

**Comment by TheUnknownCod3r** [comment]
Was about to look into this as well, since Im familiar with Content Warning code.

**Comment by MrS4turn** [comment]
need to push to prod, but seed is broken

**Comment by MrS4turn** [comment]
tested and pushed up live!
