### ISSUE TITLE
Content Warning: Items wrong again

### ISSUE THREAD

**Issue by MrS4turn** [WarpWorld/CCPack-PC-ContentWarning#3]
Another update to the game and item ids seem to be off again, example. Chorby gives brain on a stick.

**Comment by MrS4turn** [comment]
Looks like some spawns are also wrong as well.

**Comment by MrS4turn** [comment]
Ticket was opened here: https://github.com/WarpWorld/CCPack-PC-ContentWarning/issues/2

**Comment by TheUnknownCod3r** [comment]
I know this is closed, pastebin link for future referencing, contains all item names currently available in Content warning today. Will update the link as and when new items become available. https://pastebin.com/52nr2Eds
